name = "notion-api"
type = "javascript"
workers_dev = true
compatibility_date = "2021-09-19"
zone_id = ""
route = ""
account_id = ""
vars = { NOTION_TOKEN = "" }

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
